# Dockerized OSCAR EMR by Bell Eapen
# Date: May 8, 2017
# Website: http://nuchange.ca
# Updated by Clark Van Oyen from countable.ca 2019
# MySQL database shared with tomcat containers.
version: '3.0'
services:
  db:
    restart: "always"
    image: andynguyenswdev/oscar-mariadb:1023
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: liyi
      MYSQL_DATABASE: oscar_mcmaster
      MYSQL_USER: oscar
      MYSQL_PASSWORD: oscar
    volumes:
      - data:/var/lib/mysql
    networks:
      - mt-network


  # Tomcat container
  tomcat_oscar:
    restart: "always"
    image: andynguyenswdev/oscar-tomcat:1023
    command: "/wait-for-it.sh -t 0 db:3306 -- catalina.sh jpda run"
    ports:
        - 8091:8080  #HOST:CONTAINER
        - 8090:8000
    volumes:
      - webapps:/usr/local/tomcat/webapps
      - oscar-document:/var/lib/OscarDocument
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
      JDBC_URL: "jdbc:mysql://db:3306/oscar_mcmaster?autoReconnect=true&zeroDateTimeBehavior=round&useOldAliasMetadataBehavior=true&jdbcCompliantTruncation=false"
      JDBC_USER: root
      JDBC_PASS: liyi
      db_username: root
      db_password: liyi
      db_uri: "jdbc:mysql://db:3306/"
      db_name: "oscar_mcmaster?autoReconnect=true&zeroDateTimeBehavior=round&useOldAliasMetadataBehavior=true&jdbcCompliantTruncation=false"
    depends_on:
      - db
    networks:
      - mt-network
  
  adminer:
    restart: "always"
    image: adminer
    ports:
      - 8092:8080
    networks:
      - mt-network

networks:
  mt-network:
    driver: bridge

volumes:
  data:
  webapps:
  oscar-document: